[package]
name = "floccus"
version = "0.4.0-alpha.9"
authors = ["Jakub Lewandowski <scaleweather@gmail.com>"]
edition = "2024"
description = "Formulae for air thermodynamic calculations"
repository = "https://github.com/ScaleWeather/floccus"
readme = "README.md"
keywords = ["oceanography", "thermodynamics", "meteorology", "weather"]
categories = ["mathematics", "science"]
license = "Apache-2.0"
exclude = [".github/*"]

[dependencies]
thiserror = "2.0"
float-cmp = "0.10"
tracing = { version = "0.1", optional = true, default-features = false, features = [
    "attributes",
] }
ndarray = { version = "0.16", default-features = false, optional = true }
rayon = { version = "1.10", default-features = false, optional = true }
uom = { version = "0.37", default-features = false, features = [
    "si",
    "std",
    "autoconvert",
    "f32",
] }

[lib]
doctest = false

[dev-dependencies]
criterion = "0.6"
itertools = "0.14"
log = "0.4"
testing_logger = "0.1"
floccus = { path = ".", features = ["double_precision"] }

[features]
default = []
argdebug = ["dep:tracing"]
double_precision = ["uom/f64"]
array = ["dep:ndarray"]
parallel = ["array", "ndarray/rayon", "dep:rayon"]

[[bench]]
name = "equivalent_potential_temperature"
harness = false

[[bench]]
name = "mixing_ratio"
harness = false

[[bench]]
name = "potential_temperature"

[[bench]]
name = "relative_humidity"
harness = false

[[bench]]
name = "saturation_mixing_ratio"
harness = false

[[bench]]
name = "saturation_vapour_pressure"
harness = false

[[bench]]
name = "specific_humidity"
harness = false

[[bench]]
name = "vapour_pressure_deficit"
harness = false

[[bench]]
name = "vapour_pressure"
harness = false

[[bench]]
name = "virtual_temperature"
harness = false

[[bench]]
name = "wet_bulb_potential_temperature"
harness = false

[[bench]]
name = "wet_bulb_temperature"
harness = false
