[package]
name = "floccus"
version = "0.1.0"
authors = ["Jakub Lewandowski <scaleweather@gmail.com>"]
edition = "2018"
description = "Formulae for air thermodynamic calculations"
repository = "https://github.com/ScaleWeather/floccus"
readme = "README.md"
keywords = ["oceanography", "thermodynamics", "meteorology", "weather"]
categories = ["mathematics", "science"]
license = "Apache-2.0"
exclude = [
    ".github/*",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.28"
float-cmp = "0.9.0"

[dev-dependencies]
criterion = "0.3.5"

[[bench]]
name = "virtual_temperature"
harness = false

[[bench]]
name = "vapour_pressure"
harness = false

[[bench]]
name = "mixing_ratio"
harness = false

[[bench]]
name = "wet_bulb_temperature"
harness = false

[[bench]]
name = "relative_humidity"
harness = false
