[package]
name = "floccus"
version = "0.4.0"
authors = ["Jakub Lewandowski <scaleweather@gmail.com>"]
edition = "2021"
description = "Formulae for air thermodynamic calculations"
repository = "https://github.com/ScaleWeather/floccus"
readme = "README.md"
keywords = ["oceanography", "thermodynamics", "meteorology", "weather"]
categories = ["mathematics", "science"]
license = "Apache-2.0"
exclude = [
    ".github/*",
]

[dependencies]
thiserror = "1.0"
float-cmp = "0.9"
floccus-proc = {version = "0.2.5", optional = true}
log = "0.4"

[dev-dependencies]
criterion = "0.5.1"

[features]
debug = ["floccus-proc"]
double_precision = []

[[bench]]
name = "virtual_temperature"
harness = false

[[bench]]
name = "vapour_pressure"
harness = false

[[bench]]
name = "vapour_pressure_deficit"
harness = false

[[bench]]
name = "mixing_ratio"
harness = false

[[bench]]
name = "wet_bulb_temperature"
harness = false

[[bench]]
name = "relative_humidity"
harness = false

[[bench]]
name = "specific_humidity"
harness = false

[[bench]]
name = "potential_temperature"
harness = false

[[bench]]
name = "equivalent_potential_temperature"
harness = false

[[bench]]
name = "wet_bulb_potential_temperature"
harness = false
