on: pull_request

name: Cargo Clippy

env:
    CARGO_TERM_COLOR: always
    RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check:
    name: Check

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clippy
        run: |
          rustup component add clippy
          cargo clippy -- -D warnings
